version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    ports:
      - "${ES_PORT}:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: ./local-be
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

  frontend:
    build: ./local-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  esdata:
